name: Generate PRs for new Branches
on:
  pull_request:
    branches: 
      - 'main'
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.DS_TOUR_PAT }}
        run: |
          branch=${{ github.head_ref }}
          echo "branch is $branch"
          git clone https://github.com/siddarthpatel/ds-tour.git
          cd ds-tour
          git checkout $branch
          # workspace=${{ github.workspace }}
          # echo "workspace is $workspace"
          # cd ${{ github.workspace }}
          # git init
          author=$(git show --format="%an" $branch | head -n 1)
          echo "author is $author"
          # team_members=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/{ORG}/teams/{TEAM_SLUG}/members --json login)
          # if [[ "$team_members" =~ $author ]]; then
          #   echo -e "Do nothing, since $author knows how to create PRs...""
          # else
          #   echo -e "Autogenerating PR since $author isnt part of our team"
          #   gh pr create -B main -H $branch --title 'Automated PR for branch: $branch' --body 'really long string with template'
          # fi